### ISSUE TITLE
Create bootstrap command that sets up b2g build requirements for you

### ISSUE THREAD

**Issue by ahal** [ahal/b2g-commands#14]

**Comment by nhirata** [comment]
For the Mac side, you might be able to leverage the already existing bootstrap?   curl -fsSL https://raw.github.com/mozilla-b2g/B2G/master/scripts/bootstrap-mac.sh | bash

(From https://developer.mozilla.org/en-US/Firefox_OS/Firefox_OS_build_prerequisites )

**Comment by ahal** [comment]
I added this in https://github.com/ahal/b2g-commands/commit/749ad7c97e895516a78cc4acc11933d1d32874d9

Though it is still untested on most platforms, so I'll need to set up a VM or something to try it out everywhere. Thanks I did end up using the bootstrap-mac.sh script too.
